import type { Lang } from './utils';

export interface FaqItem {
  q: string;
  a: string;
}

/**
 * Custom localized FAQ for risk/analytics calculators.
 * EN FAQ lives inline in src/pages/<slug>.astro files.
 * This file provides translations for es/pt/tr/hi/ru.
 */
export const CALCULATOR_FAQ: Record<string, Partial<Record<Lang, FaqItem[]>>> = {
  'sharpe-calculator': {
    es: [
      { q: '¿Qué es un buen ratio de Sharpe para un portafolio cripto?', a: 'Un ratio de Sharpe superior a 1,0 se considera aceptable, por encima de 2,0 es muy bueno y por encima de 3,0 es excelente. En los mercados cripto, donde la volatilidad es mucho mayor que en activos tradicionales, mantener un Sharpe por encima de 1,5 de forma sostenida se considera un rendimiento sólido.' },
      { q: '¿En qué se diferencia el ratio de Sharpe del ratio de Sortino?', a: 'El ratio de Sharpe penaliza toda la volatilidad por igual, tanto alcista como bajista. El ratio de Sortino solo penaliza la volatilidad a la baja, lo que lo hace más relevante para traders cripto que desean conservar grandes subidas sin ser penalizados por movimientos positivos de precio.' },
      { q: '¿Qué tasa libre de riesgo debo usar para calcular el Sharpe en cripto?', a: 'La mayoría de los analistas utilizan el rendimiento del bono del Tesoro de EE. UU. a 10 años (alrededor del 4-5%) o la tasa de préstamo de stablecoins en plataformas como Aave o Compound. Algunos enfoques cripto-nativos usan 0% ya que no existe un activo cripto verdaderamente libre de riesgo.' },
      { q: '¿Puede el ratio de Sharpe ser negativo?', a: 'Sí. Un ratio de Sharpe negativo significa que tu portafolio rindió menos que la tasa libre de riesgo, indicando que asumiste riesgo de volatilidad sin ser compensado por ello. En mercados bajistas cripto, los ratios de Sharpe negativos son comunes para estrategias de comprar y mantener.' },
      { q: '¿Con qué frecuencia debo recalcular el ratio de Sharpe de mi portafolio?', a: 'Recalcula mensual o trimestralmente usando al menos 30 puntos de datos. En los mercados cripto, que se mueven rápidamente, un Sharpe móvil de 90 días da una imagen más actual que los cálculos anuales, que pueden incluir regímenes de mercado obsoletos.' },
      { q: '¿Funciona el ratio de Sharpe específicamente para Bitcoin?', a: 'Sí, pero interpreta los resultados con cuidado. La alta volatilidad de Bitcoin puede reducir el ratio de Sharpe incluso cuando los rendimientos absolutos son fuertes. Compara el Sharpe de Bitcoin con el de otros criptoactivos en lugar de acciones tradicionales para un benchmark más significativo.' },
    ],
    pt: [
      { q: 'Qual é um bom índice de Sharpe para um portfólio cripto?', a: 'Um índice de Sharpe acima de 1,0 é geralmente considerado aceitável, acima de 2,0 é muito bom e acima de 3,0 é excelente. Nos mercados cripto, onde a volatilidade é muito maior que em ativos tradicionais, manter um Sharpe acima de 1,5 de forma sustentada é considerado um desempenho sólido.' },
      { q: 'Qual a diferença entre o índice de Sharpe e o índice de Sortino?', a: 'O índice de Sharpe penaliza toda a volatilidade igualmente — tanto de alta quanto de baixa. O índice de Sortino penaliza apenas a volatilidade negativa, tornando-o mais relevante para traders cripto que desejam manter grandes altas sem serem penalizados por movimentos positivos de preço.' },
      { q: 'Qual taxa livre de risco devo usar no cálculo do Sharpe em cripto?', a: 'A maioria dos analistas usa o rendimento do título do Tesouro dos EUA de 10 anos (cerca de 4-5%) ou a taxa de empréstimo de stablecoins em plataformas como Aave ou Compound. Algumas abordagens cripto-nativas usam 0%, pois não existe um ativo cripto verdadeiramente livre de risco.' },
      { q: 'O índice de Sharpe pode ser negativo?', a: 'Sim. Um índice de Sharpe negativo significa que seu portfólio rendeu menos que a taxa livre de risco, indicando que você assumiu risco de volatilidade sem ser compensado por isso. Em mercados de baixa cripto, índices de Sharpe negativos são comuns para estratégias de comprar e manter.' },
      { q: 'Com que frequência devo recalcular o índice de Sharpe do meu portfólio?', a: 'Recalcule mensal ou trimestralmente usando pelo menos 30 pontos de dados. Nos mercados cripto, que se movem rapidamente, um Sharpe móvel de 90 dias dá uma visão mais atual do que cálculos anuais, que podem incluir regimes de mercado desatualizados.' },
      { q: 'O índice de Sharpe funciona especificamente para o Bitcoin?', a: 'Sim, mas interprete os resultados com cautela. A alta volatilidade do Bitcoin pode diminuir o índice de Sharpe mesmo quando os retornos absolutos são fortes. Compare o Sharpe do Bitcoin com outros criptoativos em vez de ações tradicionais para um benchmark mais significativo.' },
    ],
    tr: [
      { q: 'Kripto portföyü için iyi bir Sharpe oranı nedir?', a: '1,0 üzerindeki Sharpe oranı genellikle kabul edilebilir, 2,0 üzeri çok iyi ve 3,0 üzeri mükemmel kabul edilir. Volatilitenin geleneksel varlıklardan çok daha yüksek olduğu kripto piyasalarında sürdürülebilir bir şekilde 1,5 üzerinde Sharpe elde etmek güçlü bir performans sayılır.' },
      { q: 'Sharpe oranı ile Sortino oranı arasındaki fark nedir?', a: 'Sharpe oranı tüm volatiliteyi eşit şekilde cezalandırır — hem yukarı hem aşağı yönlü. Sortino oranı ise yalnızca aşağı yönlü volatiliteyi cezalandırır. Bu, pozitif fiyat hareketlerinden ceza almak istemeyen kripto traderları için daha uygun bir metriktir.' },
      { q: 'Kripto Sharpe hesaplaması için hangi risksiz faiz oranını kullanmalıyım?', a: 'Çoğu analist ABD 10 yıllık Hazine tahvil getirisini (yaklaşık %4-5) veya Aave ya da Compound gibi platformlardaki stablecoin borç verme faizini kullanır. Bazı kripto-yerli yaklaşımlar, gerçek anlamda risksiz bir kripto varlık olmadığı için %0 kullanır.' },
      { q: 'Sharpe oranı negatif olabilir mi?', a: 'Evet. Negatif Sharpe oranı, portföyünüzün risksiz faiz oranından daha düşük getiri sağladığı anlamına gelir; yani volatilite riski aldınız ama bunun karşılığında ödüllendirilmediniz. Kripto ayı piyasalarında al ve tut stratejileri için negatif Sharpe oranları yaygındır.' },
      { q: 'Portföyümün Sharpe oranını ne sıklıkla yeniden hesaplamalıyım?', a: 'En az 30 veri noktası kullanarak aylık veya üç aylık olarak yeniden hesaplayın. Hızlı hareket eden kripto piyasalarında 90 günlük hareketli Sharpe, eski piyasa rejimlerini içerebilen yıllık hesaplamalardan daha güncel bir tablo sunar.' },
      { q: 'Sharpe oranı özellikle Bitcoin için çalışır mı?', a: 'Evet, ancak sonuçları dikkatli yorumlayın. Bitcoin\'in yüksek volatilitesi, mutlak getiriler güçlü olsa bile Sharpe oranını düşürebilir. Daha anlamlı bir kıyaslama için Bitcoin\'in Sharpe\'ını geleneksel hisse senetleri yerine diğer kripto varlıklarla karşılaştırın.' },
    ],
    hi: [
      { q: 'क्रिप्टो पोर्टफोलियो के लिए अच्छा शार्प अनुपात क्या है?', a: '1.0 से ऊपर का शार्प अनुपात आम तौर पर स्वीकार्य माना जाता है, 2.0 से ऊपर बहुत अच्छा और 3.0 से ऊपर उत्कृष्ट है। क्रिप्टो बाजारों में, जहां अस्थिरता पारंपरिक संपत्तियों से बहुत अधिक है, लगातार 1.5 से ऊपर शार्प बनाए रखना मजबूत प्रदर्शन माना जाता है।' },
      { q: 'शार्प अनुपात और सॉर्टिनो अनुपात में क्या अंतर है?', a: 'शार्प अनुपात सभी अस्थिरता को समान रूप से दंडित करता है — ऊपर और नीचे दोनों। सॉर्टिनो अनुपात केवल नीचे की ओर की अस्थिरता को दंडित करता है, जो उन क्रिप्टो ट्रेडर्स के लिए अधिक प्रासंगिक है जो सकारात्मक मूल्य चालों के लिए दंडित हुए बिना बड़ी तेजी को बनाए रखना चाहते हैं।' },
      { q: 'क्रिप्टो शार्प गणना के लिए मुझे कौन सी जोखिम-मुक्त दर का उपयोग करना चाहिए?', a: 'अधिकांश विश्लेषक अमेरिकी 10-वर्षीय ट्रेजरी यील्ड (लगभग 4-5%) या Aave या Compound जैसे प्लेटफार्मों पर स्टेबलकॉइन लेंडिंग दर का उपयोग करते हैं। कुछ क्रिप्टो-नेटिव दृष्टिकोण 0% का उपयोग करते हैं क्योंकि कोई वास्तव में जोखिम-मुक्त क्रिप्टो संपत्ति नहीं है।' },
      { q: 'क्या शार्प अनुपात नकारात्मक हो सकता है?', a: 'हाँ। नकारात्मक शार्प अनुपात का अर्थ है कि आपके पोर्टफोलियो ने जोखिम-मुक्त दर से कम रिटर्न दिया, जो दर्शाता है कि आपने अस्थिरता जोखिम उठाया लेकिन उसकी भरपाई नहीं हुई। क्रिप्टो बियर मार्केट में, बाय-एंड-होल्ड रणनीतियों के लिए नकारात्मक शार्प अनुपात आम हैं।' },
      { q: 'मुझे अपने पोर्टफोलियो का शार्प अनुपात कितनी बार पुनर्गणना करना चाहिए?', a: 'कम से कम 30 डेटा बिंदुओं का उपयोग करके मासिक या त्रैमासिक रूप से पुनर्गणना करें। तेजी से चलने वाले क्रिप्टो बाजारों में, 90-दिन का रोलिंग शार्प वार्षिक गणनाओं की तुलना में अधिक वर्तमान तस्वीर देता है, जिनमें पुराने बाजार शासन शामिल हो सकते हैं।' },
      { q: 'क्या शार्प अनुपात विशेष रूप से बिटकॉइन के लिए काम करता है?', a: 'हाँ, लेकिन परिणामों की सावधानी से व्याख्या करें। बिटकॉइन की उच्च अस्थिरता शार्प अनुपात को कम कर सकती है भले ही पूर्ण रिटर्न मजबूत हों। अधिक सार्थक बेंचमार्क के लिए बिटकॉइन के शार्प की तुलना पारंपरिक इक्विटी के बजाय अन्य क्रिप्टो संपत्तियों से करें।' },
    ],
    ru: [
      { q: 'Какой коэффициент Шарпа считается хорошим для крипто-портфеля?', a: 'Коэффициент Шарпа выше 1,0 считается приемлемым, выше 2,0 — очень хорошим, выше 3,0 — отличным. На крипто-рынках, где волатильность значительно выше, чем у традиционных активов, устойчивый Шарп выше 1,5 считается сильным результатом.' },
      { q: 'Чем коэффициент Шарпа отличается от коэффициента Сортино?', a: 'Коэффициент Шарпа штрафует всю волатильность одинаково — как восходящую, так и нисходящую. Коэффициент Сортино штрафует только нисходящую волатильность, что делает его более подходящим для крипто-трейдеров, которые хотят сохранять крупные восходящие движения без штрафа за позитивную динамику цены.' },
      { q: 'Какую безрисковую ставку использовать для расчёта Шарпа в крипте?', a: 'Большинство аналитиков используют доходность 10-летних казначейских облигаций США (около 4-5%) или ставку кредитования стейблкоинов на платформах Aave или Compound. Некоторые крипто-нативные подходы используют 0%, поскольку по-настоящему безрискового крипто-актива не существует.' },
      { q: 'Может ли коэффициент Шарпа быть отрицательным?', a: 'Да. Отрицательный коэффициент Шарпа означает, что ваш портфель показал доходность ниже безрисковой ставки — вы приняли на себя риск волатильности, но не получили за это компенсации. На медвежьих крипто-рынках отрицательные коэффициенты Шарпа типичны для стратегий «купи и держи».' },
      { q: 'Как часто нужно пересчитывать коэффициент Шарпа портфеля?', a: 'Пересчитывайте ежемесячно или ежеквартально, используя не менее 30 точек данных. На быстро меняющихся крипто-рынках скользящий 90-дневный Шарп даёт более актуальную картину, чем годовые расчёты, которые могут включать устаревшие рыночные режимы.' },
      { q: 'Работает ли коэффициент Шарпа конкретно для Биткоина?', a: 'Да, но интерпретируйте результаты осторожно. Высокая волатильность Биткоина может занижать коэффициент Шарпа даже при сильных абсолютных доходах. Для более осмысленного сравнения сопоставляйте Шарп Биткоина с другими крипто-активами, а не с традиционными акциями.' },
    ],
  },
  'sortino-calculator': {
    es: [
      { q: '¿Qué es un buen ratio de Sortino para inversiones cripto?', a: 'Un ratio de Sortino superior a 2,0 se considera bueno y por encima de 3,0 es excelente. Como el Sortino solo mide la desviación a la baja, los valores tienden a ser más altos que los ratios de Sharpe correspondientes. En cripto, un Sortino sostenido por encima de 2,0 indica una sólida gestión del riesgo bajista.' },
      { q: '¿Por qué el ratio de Sortino es mejor que el de Sharpe para cripto?', a: 'Los criptoactivos a menudo tienen grandes picos alcistas que inflan la volatilidad total. El ratio de Sharpe penaliza estos movimientos positivos, mientras que el Sortino ignora la volatilidad alcista y se enfoca solo en los movimientos bajistas perjudiciales, dando una imagen más justa del rendimiento ajustado por riesgo.' },
      { q: '¿Qué es la desviación a la baja y cómo se calcula?', a: 'La desviación a la baja mide la volatilidad de los rendimientos que caen por debajo de un rendimiento mínimo aceptable (MAR), típicamente 0% o la tasa libre de riesgo. Solo se elevan al cuadrado y promedian las desviaciones negativas, luego se toma la raíz cuadrada. Esto aísla el riesgo que realmente preocupa a los inversores: las pérdidas.' },
      { q: '¿Qué rendimiento mínimo aceptable (MAR) debo usar?', a: 'Las opciones comunes son 0% (preservación de capital), la tasa libre de riesgo (rendimiento de bonos del Tesoro o stablecoins) o tu rendimiento objetivo personal. Usar 0% es lo más simple y frecuente para portafolios cripto donde el objetivo principal es evitar pérdidas.' },
      { q: '¿Puede el ratio de Sortino ser engañoso en mercados cripto?', a: 'Sí. Durante mercados alcistas prolongados con pocos retrocesos, el Sortino puede parecer extremadamente alto porque la desviación a la baja es cercana a cero. Verifica siempre el ratio en un ciclo de mercado completo que incluya fases alcistas y bajistas para una evaluación realista.' },
      { q: '¿Cuántos puntos de datos necesito para un ratio de Sortino fiable?', a: 'Usa al menos 30 observaciones de rendimiento para significancia estadística. Los rendimientos diarios durante 3 meses o los semanales durante 6 meses son enfoques comunes. Menos datos producen resultados poco fiables, especialmente si el período careció de retrocesos significativos.' },
    ],
    pt: [
      { q: 'Qual é um bom índice de Sortino para investimentos cripto?', a: 'Um índice de Sortino acima de 2,0 é considerado bom e acima de 3,0 é excelente. Como o Sortino mede apenas o desvio negativo, os valores tendem a ser mais altos que os índices de Sharpe correspondentes. Em cripto, um Sortino sustentado acima de 2,0 indica forte gestão de risco de queda.' },
      { q: 'Por que o índice de Sortino é melhor que o Sharpe para cripto?', a: 'Criptoativos frequentemente têm grandes picos de alta que inflam a volatilidade total. O índice de Sharpe penaliza esses movimentos positivos, enquanto o Sortino ignora a volatilidade positiva e foca apenas nos movimentos negativos prejudiciais, dando uma visão mais justa do retorno ajustado ao risco.' },
      { q: 'O que é desvio negativo e como é calculado?', a: 'O desvio negativo mede a volatilidade dos retornos que ficam abaixo de um retorno mínimo aceitável (MAR), tipicamente 0% ou a taxa livre de risco. Apenas os desvios negativos são elevados ao quadrado e calculada a média, depois tira-se a raiz quadrada. Isso isola o risco que realmente importa para os investidores — as perdas.' },
      { q: 'Qual retorno mínimo aceitável (MAR) devo usar?', a: 'Opções comuns são 0% (preservação de capital), a taxa livre de risco (rendimento de títulos do Tesouro ou stablecoins) ou seu retorno-alvo pessoal. Usar 0% é o mais simples e comum para portfólios cripto onde o objetivo principal é evitar perdas.' },
      { q: 'O índice de Sortino pode ser enganoso nos mercados cripto?', a: 'Sim. Durante mercados de alta prolongados com poucos recuos, o Sortino pode parecer extremamente alto porque o desvio negativo é próximo de zero. Sempre verifique o índice ao longo de um ciclo completo de mercado que inclua fases de alta e baixa para uma avaliação realista.' },
      { q: 'Quantos pontos de dados preciso para um índice de Sortino confiável?', a: 'Use pelo menos 30 observações de retorno para significância estatística. Retornos diários ao longo de 3 meses ou semanais ao longo de 6 meses são abordagens comuns. Menos dados produzem resultados pouco confiáveis, especialmente se o período não teve quedas significativas.' },
    ],
    tr: [
      { q: 'Kripto yatırımları için iyi bir Sortino oranı nedir?', a: '2,0 üzerindeki Sortino oranı iyi, 3,0 üzeri ise mükemmel kabul edilir. Sortino yalnızca aşağı yönlü sapmayı ölçtüğü için değerler, karşılık gelen Sharpe oranlarından daha yüksek olma eğilimindedir. Kriptoda sürdürülebilir bir şekilde 2,0 üzerinde Sortino, güçlü aşağı yönlü risk yönetimini gösterir.' },
      { q: 'Sortino oranı neden kripto için Sharpe oranından daha iyidir?', a: 'Kripto varlıkları genellikle toplam volatiliteyi şişiren büyük yukarı yönlü sıçramalar yaşar. Sharpe oranı bu pozitif hareketleri cezalandırırken, Sortino oranı yukarı yönlü volatiliteyi görmezden gelir ve yalnızca zararlı aşağı yönlü hareketlere odaklanarak riske göre düzeltilmiş getirinin daha adil bir resmini verir.' },
      { q: 'Aşağı yönlü sapma nedir ve nasıl hesaplanır?', a: 'Aşağı yönlü sapma, minimum kabul edilebilir getirinin (MAR) altına düşen getirilerin volatilitesini ölçer; bu genellikle %0 veya risksiz orandır. Yalnızca negatif sapmalar kareye alınıp ortalaması hesaplanır, ardından karekök alınır. Bu, yatırımcıların gerçekten önemsediği riski — kayıpları — izole eder.' },
      { q: 'Hangi minimum kabul edilebilir getiriyi (MAR) kullanmalıyım?', a: 'Yaygın seçenekler %0 (sermaye koruma), risksiz oran (Hazine tahvil getirisi veya stablecoin getirisi) veya kişisel hedef getirinizdir. Birincil amacı kayıplardan kaçınmak olan kripto portföyleri için %0 kullanmak en basit ve en yaygın yöntemdir.' },
      { q: 'Sortino oranı kripto piyasalarında yanıltıcı olabilir mi?', a: 'Evet. Az sayıda düşüş yaşanan uzun süreli boğa piyasalarında, aşağı yönlü sapma sıfıra yakın olduğu için Sortino son derece yüksek görünebilir. Gerçekçi bir değerlendirme için oranı her zaman hem boğa hem de ayı aşamalarını içeren tam bir piyasa döngüsü üzerinden kontrol edin.' },
      { q: 'Güvenilir bir Sortino oranı için kaç veri noktası gerekir?', a: 'İstatistiksel anlamlılık için en az 30 getiri gözlemi kullanın. 3 ay boyunca günlük getiriler veya 6 ay boyunca haftalık getiriler yaygın yaklaşımlardır. Daha az veri, özellikle dönemde anlamlı düşüşler yaşanmadıysa güvenilmez sonuçlar üretir.' },
    ],
    hi: [
      { q: 'क्रिप्टो निवेश के लिए अच्छा सॉर्टिनो अनुपात क्या है?', a: '2.0 से ऊपर का सॉर्टिनो अनुपात अच्छा और 3.0 से ऊपर उत्कृष्ट माना जाता है। चूंकि सॉर्टिनो केवल नीचे की ओर के विचलन को मापता है, इसलिए मान संबंधित शार्प अनुपात से अधिक होते हैं। क्रिप्टो में, 2.0 से ऊपर का निरंतर सॉर्टिनो मजबूत डाउनसाइड जोखिम प्रबंधन को दर्शाता है।' },
      { q: 'क्रिप्टो के लिए सॉर्टिनो अनुपात शार्प अनुपात से बेहतर क्यों है?', a: 'क्रिप्टो संपत्तियों में अक्सर बड़ी तेजी होती है जो कुल अस्थिरता को बढ़ाती है। शार्प अनुपात इन सकारात्मक चालों को दंडित करता है, जबकि सॉर्टिनो अनुपात ऊपर की ओर की अस्थिरता को नजरअंदाज करता है और केवल हानिकारक नीचे की ओर के चालों पर ध्यान केंद्रित करता है, जोखिम-समायोजित रिटर्न की अधिक उचित तस्वीर देता है।' },
      { q: 'डाउनसाइड विचलन क्या है और इसकी गणना कैसे की जाती है?', a: 'डाउनसाइड विचलन उन रिटर्न की अस्थिरता को मापता है जो न्यूनतम स्वीकार्य रिटर्न (MAR) से नीचे आते हैं, आमतौर पर 0% या जोखिम-मुक्त दर। केवल नकारात्मक विचलनों को वर्ग करके औसत निकाला जाता है, फिर वर्गमूल लिया जाता है। यह उस जोखिम को अलग करता है जिसकी निवेशकों को वास्तव में चिंता है — नुकसान।' },
      { q: 'मुझे कौन सा न्यूनतम स्वीकार्य रिटर्न (MAR) उपयोग करना चाहिए?', a: 'सामान्य विकल्प हैं 0% (पूंजी संरक्षण), जोखिम-मुक्त दर (ट्रेजरी यील्ड या स्टेबलकॉइन यील्ड), या आपका व्यक्तिगत लक्ष्य रिटर्न। क्रिप्टो पोर्टफोलियो के लिए जहां प्राथमिक लक्ष्य नुकसान से बचना है, 0% का उपयोग करना सबसे सरल और सबसे आम है।' },
      { q: 'क्या सॉर्टिनो अनुपात क्रिप्टो बाजारों में भ्रामक हो सकता है?', a: 'हाँ। कम गिरावट वाले लंबे बुल मार्केट के दौरान, सॉर्टिनो बेहद ऊंचा दिख सकता है क्योंकि डाउनसाइड विचलन शून्य के करीब होता है। यथार्थवादी मूल्यांकन के लिए हमेशा बुल और बियर दोनों चरणों वाले पूर्ण बाजार चक्र पर अनुपात की जांच करें।' },
      { q: 'विश्वसनीय सॉर्टिनो अनुपात के लिए कितने डेटा बिंदु चाहिए?', a: 'सांख्यिकीय महत्व के लिए कम से कम 30 रिटर्न अवलोकन का उपयोग करें। 3 महीने में दैनिक रिटर्न या 6 महीने में साप्ताहिक रिटर्न सामान्य तरीके हैं। कम डेटा बिंदु अविश्वसनीय परिणाम देते हैं, विशेष रूप से यदि अवधि में सार्थक गिरावट नहीं हुई।' },
    ],
    ru: [
      { q: 'Какой коэффициент Сортино считается хорошим для крипто-инвестиций?', a: 'Коэффициент Сортино выше 2,0 считается хорошим, а выше 3,0 — отличным. Поскольку Сортино измеряет только нисходящее отклонение, его значения обычно выше, чем у соответствующего коэффициента Шарпа. В крипте устойчивый Сортино выше 2,0 указывает на эффективное управление нисходящим риском.' },
      { q: 'Почему коэффициент Сортино лучше коэффициента Шарпа для крипты?', a: 'Крипто-активы часто демонстрируют резкие скачки вверх, которые раздувают общую волатильность. Коэффициент Шарпа штрафует эти положительные движения, тогда как Сортино игнорирует восходящую волатильность и фокусируется только на вредных нисходящих движениях, давая более справедливую оценку доходности с поправкой на риск.' },
      { q: 'Что такое нисходящее отклонение и как оно рассчитывается?', a: 'Нисходящее отклонение измеряет волатильность доходностей, которые падают ниже минимально приемлемой доходности (MAR), обычно 0% или безрисковой ставки. Только отрицательные отклонения возводятся в квадрат и усредняются, затем извлекается квадратный корень. Это изолирует риск, который действительно волнует инвесторов — убытки.' },
      { q: 'Какую минимально приемлемую доходность (MAR) использовать?', a: 'Распространённые варианты: 0% (сохранение капитала), безрисковая ставка (доходность казначейских облигаций или стейблкоинов) или ваша персональная целевая доходность. Использование 0% — самый простой и популярный подход для крипто-портфелей, где основная цель — избежать убытков.' },
      { q: 'Может ли коэффициент Сортино вводить в заблуждение на крипто-рынках?', a: 'Да. Во время длительных бычьих рынков с редкими просадками Сортино может выглядеть чрезвычайно высоким, потому что нисходящее отклонение близко к нулю. Всегда проверяйте коэффициент за полный рыночный цикл, включающий и бычью, и медвежью фазы, для реалистичной оценки.' },
      { q: 'Сколько точек данных нужно для надёжного коэффициента Сортино?', a: 'Используйте минимум 30 наблюдений доходности для статистической значимости. Дневные доходности за 3 месяца или недельные за 6 месяцев — распространённые подходы. Меньшее количество данных даёт ненадёжные результаты, особенно если в периоде не было значимых просадок.' },
    ],
  },
};
